---

rabbit:
  host: rabbit
  port: 5672
  vhost: /
  user: guest
  pass: guest
  admin_pass: janusoverlord
  level: error

queues:
  standard:
    from: from-janus
    to: to-janus
  admin:
    from: from-janus-admin
    to: to-janus-admin

janus:
  session:
    keepalive: 55
  plugins:
    - janus.plugin.echotest
    - janus.plugin.videoroom
    - janus.plugin.sip

gem:
  cluster:
    enabled: true
  log:
    level: info
    type: file
    option: 'log/ruby-rabbitmq-janus.log'
  listener:
    public: 'app/ruby_rabbitmq_janus/action_events'
    admin: 'app/ruby_rabbitmq_janus/action_admin_events'
  environment : 'development'
  orm: <%= ENV['MONGO'].eql?('true') ? 'mongoid' : 'active_record' %>
  program_name: 'ruby_rabbitmq_janus'
  response_path: 'spec/supports/rrj/responses'
  process: 1
