---

detectors:
  BooleanParameter:
    enabled: false

  DataClump:
    max_copies: 4

  DuplicateMethodCall:
    allow_calls:
      - 'Tools::Log.instance'

  TooManyStatements:
    enabled: true
    max_statements: 8

  UtilityFunction:
    public_methods_only: true

exclude_paths:
  - lib/rrj/errors/janus/responses/code.rb
  - lib/rrj/janus/responses/response.rb
