---

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'Rakefile'
    - 'lib/tasks/*'
    - 'lib/generators/**/*'
    - 'gemfiles/*'
  TargetRubyVersion: 2.3

# Styles rules
# ###
Style/Encoding:
  Enabled: true

Style/Documentation:
  Enabled: true
  Exclude:
    - lib/rrj/errors/**/*

Style/RescueStandardError:
  Enabled: false

# Metrics Rules
# ###
Metrics/LineLength:
  Max: 80
  Exclude:
    - spec/**/*
    - lib/rrj/errors/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - ruby_rabbitmq_janus.gemspec

# Naming rules
# ###
Naming/RescuedExceptionsVariableName:
  PreferredName: exception

# RSpec
# ###
RSpec/BeforeAfterAll:
  Exclude:
    - spec/ruby_rabbitmq_janus/tools/config_spec.rb

RSpec/DescribeClass:
  Exclude:
    - spec/request/**/*

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false
