---

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  RubyInterpreters:
    - ruby

# Styles rules
# ###
Style/Documentation:
  Enabled: true
  Exclude:
    - lib/rrj/errors/**/*

Style/Encoding:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - bin/ruby_rabbitmq_janus
    - gemfiles/*

Style/StringLiterals:
  Enabled: true
  Exclude:
    - gemfiles/*

Style/RescueStandardError:
  Enabled: false

# Metrics Rules
# ###
Metrics/LineLength:
  Max: 80
  Exclude:
    - spec/**/*
    - lib/rrj/errors/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - ruby_rabbitmq_janus.gemspec

# Naming rules
# ###
Naming/RescuedExceptionsVariableName:
  PreferredName: exception

# RSpec
# ###
RSpec/BeforeAfterAll:
  Exclude:
    - spec/ruby_rabbitmq_janus/tools/config_spec.rb

RSpec/DescribeClass:
  Exclude:
    - spec/request/**/*

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false
