AllCops:
  Exclude:
    - Gemfile
    - rrj.gemspec
  TargetRubyVersion: 2.3

Style/Encoding:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Metrics/LineLength:
  Max: 90
