AllCops:
  Exclude:
    - 'bin/**/*'
    - 'Rakefile'
    - 'lib/tasks/*'
  TargetRubyVersion: 2.3

Style/Encoding:
  Enabled: true

Style/Documentation:
  Enabled: true
  Exclude:
    - lib/rrj/errors/**/*

Metrics/LineLength:
  Max: 80
  Exclude:
    - spec/**/*
    - lib/rrj/errors/**/*


Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - ruby_rabbitmq_janus.gemspec
