---

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  RubyInterpreters:
    - ruby
  NewCops: enable

# Layout rules
# ###
Layout/LineLength:
  Max: 80
  Exclude:
    - ruby_rabbitmq_janus.gemspec
    - spec/**/*
    - lib/rrj/errors/**/*
    - lib/rrj/rails.rb

# Lint rules
# ###
Lint/EmptyBlock:
  Exclude:
    - spec/ruby_rabbitmq_janus/rabbit/**/*.rb
Lint/UselessMethodDefinition:
  Exclude:
    - lib/rrj/errors/rabbit/rabbit.rb

# Metrics Rules
# ###
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - ruby_rabbitmq_janus.gemspec

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/rrj/tools/replaces/type.rb
Metrics/MethodLength:
  Exclude:
    - lib/rrj/rabbit/connect.rb

# Naming rules
# ###
Naming/RescuedExceptionsVariableName:
  PreferredName: exception

# Styles rules
# ###
Style/Documentation:
  Exclude:
    - lib/rrj/errors/**/*
Style/FrozenStringLiteralComment:
  Exclude:
    - bin/ruby_rabbitmq_janus
    - gemfiles/*
Style/StringLiterals:
  Exclude:
    - gemfiles/*
Style/RescueStandardError:
  Enabled: false
Style/HashConversion:
  Exclude:
    - lib/rrj/tools/gem/config/rabbit.rb

# RSpec
# ###
RSpec/BeforeAfterAll:
  Exclude:
    - spec/ruby_rabbitmq_janus/tools/config_spec.rb
RSpec/DescribeClass:
  Exclude:
    - spec/request/**/*
RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
RSpec/MultipleMemoizedHelpers:
  Max: 10
RSpec/FilePath:
  Exclude:
    - spec/ruby_rabbitmq_janus/rabbit/listener/from_spec.rb
    - spec/ruby_rabbitmq_janus/rabbit/publisher/base_spec.rb
