sudo: required
dist: trusty
group: deprecated-2017Q4
language: ruby

cache:
  bundler: true
  directories:
    - /home/travis/.rvm
    - /usr/local/bundle

rvm:
  - 2.6
  - 2.5

gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile

env:
  DOCKER_COMPOSE_VERSION: 1.24.1

services:
  - docker

before_install:
  - gem update --system
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose build
  - docker-compose up -d rabbit
  - sleep 15
  - docker-compose up -d janus janus_token

script:
  - docker-compose run gem env MONGO=true bundle exec rake spec
  - docker-compose run gem env MONGO=false bundle exec rake spec
    #- docker-compose run gem env MONGO=true bundle exec rake concurrency
    #- docker-compose run gem env MONGO=false bundle exec rake concurrency

jobs:
  include:
    - rvm: 2.5
      gemfile:
        - gemfiles/rails_4.gemfile
        - gemfiles/rails_5.gemfile
        - gemfiles/rails_6.gemfile
      script:
        - docker-compose run gem env MONGO=true bundle exec rake concurrency
        - docker-compose run gem env MONGO=false bundle exec rake concurrency
    - stage: test
      if: branch = master
      name: 'Linter execution'
      script:
        - docker-compose run gem rubocop -D
        - docker-compose run gem reek -D
    - stage: deploy
      script: skip
      deploy: &rubygems
        provider: rubygems
        api_key:
          secure: OWuVCekC/FzcZtxbvItOiJmbje9Xo29TdBcb8+HXVtxSJYTpRYlX+/QS6VbvznOX8WHkQ+0n8EkKJlzFnqBncat2JXyOa/VS+S1cL4E7OT1cieNXMPWpCB+5O49nS+OSX90ls5nyFl6iCLLVmzunLUCElfHjySWxHXtu/91kVE7YGCDuU+nsnRdU4N9rMBNzn04r1ygKcl7WjuZ7uytt4bX+fbdAPfP1EFa1iuRWzqnqZqleNDsdYMLWVsKtBRY+eXw65u2+xGVTBs9HGC5cHZ65zjV+XiL4fJIfxXqA4qdCaEH/CkQVVdF8IUyJu5xEi6GkCQaEgC7LaNY90ca2Qh3WBnsC0QD2xgYQLxs/gnAyBOXtlZis6RnQdHeCN60lUdSX0M4lTX+7M++Iva6VVepZ2NxIWUvEbD/FGO9XuWX2TSncTk3tfmf+i173CS5XT6ahW6QJ4Bt/VDc2NAV/Y7SI3JOuthWt1rwornN8Qm3BqrrZ+xibSwMKxxnitbSREUvQG/YBCRuWuBJK+XahZc/lcXWrTXVRzGk9gOZHRJjaMamXvv9g860ansxLCXQ5OOW/HFt4PBxNhRUOuMNaVTTp8plbRsmfUtxPPntrfXUnB/P/pD7FyfkJPfQaizZCUrS4ecA7YNqtsBIOsQGrkYqakf4tWe5JxMKOsBB7d9Y=
        gem: ruby_rabbitmq_janus
        on:
          repo: dazzl-tv/ruby-rabbitmq-janus
          all_branches: true
        skip_cleanup: true

before_deploy:
  - gem install dpl

notifications:
  email: false
  slack:
    on_success: always
    rooms:
      secure: wq9V5QaS9tQPr0gaHtRCuLPbMei+gO6tHNwkDFbNUo9SFb1W/0zdxapnxQhxIcyqYfLanvnjprQHme3OXJnVP59jbG4CIfe0NMcOO4s+DYBJvEBEj2+li263A96mJCdXxVojDEZ83E/0+PppfNut+CBtvWikAkMyvvbPNyd0XkQ7dYK6iWEdLBRjDmC8HYRPZgLAcHADB85F60/BuUwsWkZhCyymAXU1McPVFu8OMBpb7LJhLy9MqB5W6VpOlmUYDeTasl5h+tV7ci2cr8Mcu6EAuSUWMG/bBm57z65cEG7kz750gw1Vt8h+mUgcmWfsXBbsJZrh7xpHOulynMcf0rwVcqanvfb9suHYHf0HXon9+ljlwbP2J91wrQqezmvZqhpekPYXD3Qz8qCtdSzhSOdVzE6LaAtDKrj6p9CJ1hwhp5tWUA1roz8pNdKCOHNkmcrWCOggnhDlxrBkwwVoDvVfIl9yL1kezL87mD8vRrSJWRzKjoE85fjFJM9JR6Ie/Bcf4FjWeWRNwAv4LrLOUBDI8Bs0KNdsw+pK/69EEG5N5gnqGmqs6KOY7Ucs75Hq3ZWop85GFocQnw0k4U6YarDvzrTKz/hcrSTCwnNG8jkpKRQ6x+76rlLPcXwaGkL34AmVJ7SFu8a5u8UJUYigPej6c58rBg5wwcvw++izUKg=
