sudo: required

cache: bundler

language: ruby

rvm:
  - 2.3.1

env:
  DOCKER_COMPOSE_VERSION: 1.8.1

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose up -d rabbit

script:
  - docker-compose up -d janus
  - docker-compose run gem bundle exec rake
