sudo: required

cache: bundler

language: ruby

rvm:
  - 2.3.1

env:
  DOCKER_COMPOSE_VERSION: 1.8.1

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose build
  - docker-compose up -d rabbit
  - sleep 30
  - docker-compose logs rabbit
  - docker-compose up -d janus
  - sleep 30
  - docker-compose logs janus

script:
  - docker-compose run gem bundle exec rake

deploy:
  provider: rubygems
  gemspec: rrj.gemspec
  gem: ruby_rabbitmq_janus
  on:
    branch: master
    repo: dazzl-tv/ruby-rabbitmq-janus
  skip_cleanup: true
  user: jeremy.vaillant@dazzl.tv
  api_key:
    secure: gIQXc5+Pcnb3YCOiDScxnRgXRmYQ/nqjoApYLGlBV9US3IpiHO1wNP9y/6fvjwJuZ/+CfR5d1hdotBjHRfrQP4UHUYfFFb3Ut3L7YMPTCSofv868aVSInocuivCxpK2Hwa54udoqbjsDc7NpDLhTd8ztFVouMdbXoF1cOCMKr3pboPvlcouI52eOC5qK6XVGwzO1iGPaacvFdUbXDD/EeAWZru7wd1QYozfhATQu1UgDpbyUEeLQ8cXdnhPx/AsBG9qRSjaUdOsEmla21DaIGwFoqFkMctceZ0Rpo+GIGF0+ejiRn42+Rm/hA6uJnGqMxzwJmZo7XOayCTAGCnsLQ3SAKTb6c8+OX2waJmcLW2L14PQlElKFrUVBGZlZwz1AK3LN7M28rLAJlVO+KUhTn09msy8tr5U/v7pcHYQcfoO/eTj6n13UOKzRaqY8ST+d+rAunp/DXAprqv/IzJzZDISmsh00JtWJLQwWlYw51ej5wqB5MEQ0qD5uGbVFKsyW7g5zazVkrbQc4uRihyHY38Isrl1ylPcVqf5XDMvbdFwQ2nE/DirxsB57BkCx1mxuruu+Tdzw2koMa00AAMm5irXcOxUKQxdFKMLd2WwyzUZWl05iBb5vNICAqdqmtrprPhLhT8iiM/LxL20KkU6T+yJmqmbzP0Ykt3iF0n+RE8k=

notifications:
  email: false
  slack:
    on_success: always
    circle-ci:
      secure: fsBTrAviRFIUYvkbrv6v4/jQFaeeEYWxJJrqq9N6/W+E3Xa9UTT2TMo0GH+l45DXm1lnLTEmaWcYPsedKLUw2zA+pHhi3jdOO2ge55hE0ZEWrmDPDMObwNWx8dA+3AHCr5L2m5WtnURdVgSveT/rhb8UB95pjO85+d2tfVCbTacT4LhiBxtX+i3HKAVCrorpHsg/mE1o8rZEx8y5itoTkOuN690jK3F3mPR5ARezvMjAHRueJVnIZPaVJWsyZFCjrinIX30WD6gwO4BU02p48KMkxbOTaoBD4yvwSXgM/lXq2UWrKVoKWI1o3Eobx9vWx6EzdpvbyIJEIWqbhRBty0WYCQC3Msz6FoyudOaTGIQ9lRhKwD9+41Qs/jrh9xeNCPzlEXNGpm755YejWXH6w8QAigi7xfLaan69TOMHDRENYUdCQhL0VnbiRLpV+Ij4VTSHs1ZaCuTwevTcdttPFaWQ6/zYCwj/E90WYWq/z1Ww7znqTaPEVu3PXJPH9Qk9ta5wy5Yrt6Qgs6y3pydlB39EsV+DqvOicmPme89xhvXg2xaxV1tdOygPNRyOXGwVc61nlfnyycosLdQ94wkSb7Iy5z3wvsnB0gFpy99FfCnJh4ux7ieDPyIYAgEPgbTuoc9jvuc7UcYo0kaQ7Fc1GRBpHK+sbqDy5a44XY93Yq0=
