sudo: required

cache: bundler

language: ruby

rvm:
  - 2.3.1

services:
  - docker

before_install:
  - gem install bundler -v 1.12.5
  - docker run --name rabbit -p 127.0.0.1:5672:5672 -d rabbitmq:3
  - docker run --name janus --link rabbit -d quay.io/dazzl/janus-gateway

script: bundle exec rake
