sudo: required

cache: bundler

language: ruby

rvm:
  - 2.3.1

env:
  DOCKER_COMPOSE_VERSION: 1.8.1

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose build
  - docker-compose up -d rabbit
  - sleep 30
  - docker-compose logs rabbit
  - docker-compose up -d janus
  - sleep 30
  - docker-compose logs janus

script:
  - docker-compose run gem bundle exec rake

deploy:
  provider: rubygems
  gemspec: rrj.gemspec
  gem: ruby_rabbitmq_janus
  on:
    branch: master
    repo: dazzl-tv/ruby-rabbitmq-janus
  skip_cleanup: true
  api_key:
    secure: imZXI4gLQ6pGoKHgUiPZQBgcJiHmTK4HsbVtKxUX3ljbjYzuN6DYyEF9qSfJoWPHLhB0QhMOHtGOknOnPLR43mjPg+E5z/XcwDHra1qdkhksHtmUUKIT3AJWnHQW3VCKof1zFGn/zve3HJu9JYMCv0+IpWYAV/4Iw9wfUiKCc/TvX+22SBSHCmjCZ9baVtLj2TuYsPb0MEGn4fQKylLnvCY/EINdVlekAIU5Gj5tGdpOwBFd38DmW7FvXWP8y+cTbgjvJs1lhqqLB6b9MhQCQfXUPVq6YoXQ9gF5IGjNNFLg21WQw+Ip237l7s+le3M4nuirxOEzxFu6TduIk4U7iJXacpw+C5k8E/miOuofs16zCeN31ZmtywkUTuv/D4od6llGgz1PYXUxoZvm0l6Jn3SiDyepKRpqu1lZGPHkajx0sGBDScSG2v1/HRx1UXyVR58e0++Xy927hbq0YXidR1tpZmxzDgxDzkuGwGLbIYNq5GIHl+AMdq8L5+won4d9RXsVON+nbiuFT1F7T9MdFxDRRHbYM5asvBpDK1fyyhBfALpfbi0wcNmFg4PGXSI5oCjHDtboCoNnQwJSQKrwxYLA3UULSigqTnYvwNkteftb38dT5Quv1c5lrtJNbX44JRga5tCJQ9DYBiks3SegvI2GJI8cbOrk1eaoAohWgWQ=

notifications:
  email: false
  slack:
    on_success: always
    rooms:
      secure: wq9V5QaS9tQPr0gaHtRCuLPbMei+gO6tHNwkDFbNUo9SFb1W/0zdxapnxQhxIcyqYfLanvnjprQHme3OXJnVP59jbG4CIfe0NMcOO4s+DYBJvEBEj2+li263A96mJCdXxVojDEZ83E/0+PppfNut+CBtvWikAkMyvvbPNyd0XkQ7dYK6iWEdLBRjDmC8HYRPZgLAcHADB85F60/BuUwsWkZhCyymAXU1McPVFu8OMBpb7LJhLy9MqB5W6VpOlmUYDeTasl5h+tV7ci2cr8Mcu6EAuSUWMG/bBm57z65cEG7kz750gw1Vt8h+mUgcmWfsXBbsJZrh7xpHOulynMcf0rwVcqanvfb9suHYHf0HXon9+ljlwbP2J91wrQqezmvZqhpekPYXD3Qz8qCtdSzhSOdVzE6LaAtDKrj6p9CJ1hwhp5tWUA1roz8pNdKCOHNkmcrWCOggnhDlxrBkwwVoDvVfIl9yL1kezL87mD8vRrSJWRzKjoE85fjFJM9JR6Ie/Bcf4FjWeWRNwAv4LrLOUBDI8Bs0KNdsw+pK/69EEG5N5gnqGmqs6KOY7Ucs75Hq3ZWop85GFocQnw0k4U6YarDvzrTKz/hcrSTCwnNG8jkpKRQ6x+76rlLPcXwaGkL34AmVJ7SFu8a5u8UJUYigPej6c58rBg5wwcvw++izUKg=
