sudo: required

cache: bundler

language: ruby

rvm:
  - 2.3.1

branches:
  only:
    - develop
    - master

env:
  DOCKER_COMPOSE_VERSION: 1.8.1

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose up -d rabbit

script:
  - docker-compose up -d janus
  - docker-compose run gem bundle exec rake

deploy:
  provider: rubygems
  api_key: 'a0f3881aca2f1b0862183688bfdec9a5'
  gemspec: rrj.gemspec
  on:
    branch: master
