version: '2'

services:
  gem:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - rabbit
      - mongo

  rabbit:
    image: rabbitmq
    ports:
      - 5672:5672

  janus:
    build:
      context: ./.travis
      dockerfile: Dockerfile.janus
    links:
      - rabbit

  janus2:
    build:
      context: ./.travis
      dockerfile: Dockerfile.janus2
    links:
      - rabbit

  mongo:
    image: mongo
