version: '3'

services:
  gem2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: 2-alpine
    links:
      - rabbit
      - mongo
    volumes:
      - ./:/ruby_rabbitmq_janus/

  gem3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: 3-alpine
    links:
      - rabbit
      - mongo
    volumes:
      - ./:/ruby_rabbitmq_janus/

  rabbit:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672

  janus:
    image: canyan/janus-gateway:latest
    links:
      - rabbit
    container_name: janus
    volumes:
      - .github/janus.jcfg:/usr/local/etc/janus/janus.jcfg
      - .github/janus.transport.rabbitmq.jcfg:/usr/local/etc/janus/janus.transport.rabbitmq.jcfg

  janus_token:
    image: canyan/janus-gateway:latest
    links:
      - rabbit
    container_name: janus_token
    volumes:
      - .github/janus.token.jcfg:/usr/local/etc/janus/janus.jcfg
      - .github/janus.token.transport.rabbitmq.jcfg:/usr/local/etc/janus/janus.transport.rabbitmq.jcfg

  mongo:
    image: mongo
    ports:
      - 5555:27017
