version: '3'

services:
  gem:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - rabbit
      - mongo
    volumes:
      - ./spec/:/ruby_rabbitmq_janus/spec

  rabbit:
    image: rabbitmq:alpine
    ports:
      - 5672
      - 15672:15672

  janus:
    build:
      context: .travis
      dockerfile: janus.1.dockerfile
    links:
      - rabbit
    container_name: janus

  janus_token:
    build:
      context: .travis
      dockerfile: janus.2.dockerfile
    links:
      - rabbit
    container_name: janus_token

  mongo:
    image: mongo
