# Rabbit information connection
rabbit:
  # Precise RabbitMQ host - Default 'localhost'
  host: localhost
  # Precise RabbitMQ port - Default '5672'
  port: 5672
  # Precise RabbitMQ vhost - Default '/'
  vhost: /
  # Precise RabbitMQ user - Default 'guest'
  user: guest
  # Precise RabbitMQ password - Default 'guest'
  pass: guest
    # Password for admin request
  admin_pass: janusoverlord

# RabbitMQ Queue information
queues:
  # Queue sending response to janus server
  queue_from: from-janus
  # Queue sending a message for janus server
  queue_to: to-janus
    # Queues for admin janus
  admin:
    queue_from: from-janus-admin
    queue_to: to-janus-admin

# Janus plugin used
janus:
  # Create an array to plugin
  plugins:
    - janus.plugin.echotest

# Options gem
gem:
  # Option for logs
  log:
    # Define level to log
    # UNKNOW, FATAL, ERROR, WARN, INFO, DEBUG
    level: INFO
  # Option for sessions
  session:
    # Define time to send a keepalive message in seconds
    keepalive: 45
  # Option for used multi thread
  thread:
    # Boolean for activate options thread
    enable: false
    # Number of core
    number: 1
