# Rabbit information connection
rabbit:
  # Precise RabbitMQ host - Default 'localhost'
  host: localhost
  # Precise RabbitMQ port - Default '5672'
  port: 5672
  # Precise RabbitMQ vhost - Default '/'
  vhost: /
  # Precise RabbitMQ user - Default 'guest'
  user: guest
  # Precise RabbitMQ password - Default 'guest'
  pass: guest
  # Password for admin request
  admin_pass: janusoverlord
  # Logger level for rabbitmq message
  level: info
  # Test execution (with rspec ...)
  test: false

# RabbitMQ Queue information
queues:
  standard:
    # Queue sending response to janus server
    from: from-janus
    # Queue sending a message for janus server
    to: to-janus
  admin:
    # Queue sending response to admin API janus
    from: from-janus-admin
    # Queue sending a message for admin API janus
    to: to-janus-admin
  # Name to queue for managing instances
  instance: janus-instance-thread

# Janus plugin used
janus:
  # Option for sessions
  session:
    # Define time to send a keepalive message in seconds
    keepalive: 55
  # Create an array to plugin
  plugins:
    - janus.plugin.echotest
    - janus.plugin.videoroom
    - janus.plugin.sip

# Options gem
gem:
  # Options for clusturing Janus Instance
  cluster:
    # Enable/Disable cluster mode
    # if you disable cluster mode, the initializer to this gem start a session
    # automatically with Janus, but if you enable think to start a session for
    # each instance
    enabled: true
  # Option for logs
  log:
    # Define level to log
    # UNKNOW, FATAL, ERROR, WARN, INFO, DEBUG
    level: debug
  # Options for listener thread
  listener:
    # Represent path to action_events class in project who use this gem
    path: 'app/ruby_rabbitmq_janus'
