# Configuration file for gem
server:
  # Precise RabbitMQ host - Default 'localhost'
  host: localhost
  # Precise RabbitMQ port - Default 'port'
  port: 5672
  # Precise RabbitMQ vhost - Default '/'
  vhost: /
  # Precise RabbitMQ user - Default 'guest'
  user: guest
  # Precise RabbitMQ password - Default 'guest'
  password: guest

# RabbitMQ Queue information
queues:
  # Queue sending response to janus server
  queue_from: from-janus
  # Queue sending a message for janus server
  queue_to: to-janus

# Janus plugin used
janus:
  # Create an array to plugin
  plugins:
    - janus.plugin.echotest

# Options gem
gem:
  # Option for logs
  log:
    # Define level to log
    # UNKNOW, FATAL, ERROR, WARN, INFO, DEBUG
    level: INFO
