# RabbitMQ server info
server:
  # Precise RabbitMQ host
  host: 'localhost'
  # Precise RabbitMQ port
  port: 5672
  # Precise RabbitMQ vhost
  vhost: '/'
  # Precise RabbitMQ user
  user: guest
  # Precise RabbitMQ password
  password: guest

# RabbitMQ Queue information
queues:
  queue_from: from-janus
  queue_to: to-janus
