rabbit:
  host: rabbit
  port: 5672
  vhost: /
  user: guest
  pass: guest
  admin_pass: janusoverlord
  level: info
  test: false

queues:
  standard:
    from: from-janus
    to: to-janus
  admin:
    from: from-janus-admin
    to: to-janus-admin
  instance: janus-instance-thread

janus:
  session:
    keepalive: 55
  plugins:
    - janus.plugin.echotest
    - janus.plugin.videoroom
    - janus.plugin.sip

gem:
  cluster:
    enabled: false
  log:
    level: debug
    type: stdout
    option: ''
  environment : 'development'
  orm: 'mongoid'
  program_name: 'ruby_rabbitmq_janus'
