FROM quay.io/dazzl/janus-gateway

COPY janus.cfg.2 /usr/local/etc/janus/janus.cfg
COPY janus.transport.rabbitmq.cfg.2 /usr/local/etc/janus/janus.transport.rabbitmq.cfg

ENTRYPOINT ["/usr/local/bin/janus"]
CMD ["-d7"]
