FROM quay.io/dazzl/janus-gateway

RUN mkdir /usr/local/lib/janus/plugins

COPY janus.cfg /usr/local/etc/janus/janus.cfg
COPY janus.transport.rabbitmq.cfg /usr/local/etc/janus/janus.transport.rabbitmq.cfg

ENTRYPOINT ["/usr/local/bin/janus"]
CMD ["-d7"]
