---

name: Linter

on:
  push:
    branches:
      - bugfix/*
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter: ['rubocop', 'reek --single-line .']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install gems
      run: |
        gem install --no-document bundler:2.2.16
        bundle install
    - name: Run linters
      run: bundle exec ${{ matrix.linter }}
