---

name: RSpec

on:
  pull_request:
    branches:
      - develop
  push:
    branches-ignore:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6']
        # ruby-version: ['2.6', '2.7', '3.0']
        # database: ['MONGO', 'SQLITE']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Set up Janus Gateway
      # uses: dazzl-tv/janus-gateway-action@v1.0.1
      shell: bash
      run: |
        docker pull canyan/janus-gateway:latest
        docker run -d --link="rabbit" -v .github/janus.transport.rabbitmq.jcfg:/usr/local/etc/janus/janus.transport.rabbitmq.jcfg .canyan/janus-gateway:latest
    - name: Run tests
      run: bundle exec rake
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: "${{secrets.CC_TEST_REPORTER_ID}}"
      with:
        coverageLocations: |
          ${{github.workspace}}/coverage/coverage.json:simplecov

    services:
      mongo:
        image: mongo
      mysql:
        image: mariadb
      rabbit:
        image: rabbitmq
        ports:
          - 5672:5672
